#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
# Tomcat Port:
server:
  port: ${CONFIG_SERVER_EXPOSE:8888}

##---------------------------------------------------------------------------##
# Note: Show sensitive information for endpoints:
endpoints:
  sensitive: true

##---------------------------------------------------------------------------##
# Note: Security for endpoints:
management:
  security:
    enabled: false

##---------------------------------------------------------------------------##
# Note: Enable BASIC Authentication:
security:
  basic:
    enabled: true
  user:
    name: ${CLOUD_CONFIG_USERNAME:user1}
    password: ${CLOUD_CONFIG_PASSWORD:changeme}


##---------------------------------------------------------------------------##
# Note: Config Repo:
spring:
  cloud:
    config:
      server:
        git:
          # NOTE: Look for System variable 'CLOUD_CONFIG_REPO' or (:) use default
          uri: ${CLOUD_CONFIG_REPO:file:///${HOME}/microservices_config_repo}

          # NOTE: Could also have remote repositories with credentials:
#          uri: ${CLOUD_CONFIG_REPO:https://github.com/mickknutson/spring-cloud-config-repo}
#          username: ${CLOUD_CONFIG_REPO_USERNAME:bob}
#          password: ${CLOUD_CONFIG_REPO_PASSWORD:strongpassword}

        # TODO: Revisit:
        # Health Indicator
        health:
          repositories:
            microservices-client-default:
              label: v.3.0
            microservices-client-dev:
              name: microservices-client
              profiles: dev
#              label: HOTFIX


##---------------------------------------------------------------------------##
# Note: Disable server side decryption:
#spring.cloud.config.server.encrypt.enabled: false


##---------------------------------------------------------------------------##
## NOTE: TLS Profile Properties
## to use: run with:
##  Argument: "-Dspring.profiles.active=TLS
##  or System Property: "spring_profiles_active=TLS
---

spring:
  profiles: TLS

## TLS over HTTP/1.1:
## https://localhost:8443
server:
  port: 8443
  ssl:
    enabled: true
    keyStore: "classpath:keys/cloudconfig_clientauth.p12"
    keyStorePassword: changeit
    keyStoreType: PKCS12
    keyAlias: cloudconfigclient
    protocol: TLS
    trustStore: "classpath:keys/cloudconfig_clientauth.truststore"
    trustStorePassword: changeit


##---------------------------------------------------------------------------##
##---------------------------------------------------------------------------##
